# Node.js rasmi (eng so‘nggi LTS versiya)
FROM node:22

# ishchi katalog
WORKDIR /app

# package.json va package-lock.json ni ko‘chiramiz
COPY package*.json ./

# dependencylarni o‘rnatamiz
RUN npm install

# qolgan kodni ko‘chiramiz
COPY . .

# NestJS production build qilish
RUN npm run build

# konteyner ishga tushganda bajariladigan buyruq
CMD ["node", "dist/main.js"]
